// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxPxtT4ocLPeitV8mfRGnRWR5BtzjUTw',
    appId: '1:1076947278008:android:0313e95bc9a7a73141bc4d',
    messagingSenderId: '1076947278008',
    projectId: 'banx-61dcf',
    storageBucket: 'banx-61dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLwP-gnfJpZpMGZUL9770_IJ4d1TrVN3U',
    appId: '1:1076947278008:ios:bfb5d67e4f23cc5f41bc4d',
    messagingSenderId: '1076947278008',
    projectId: 'banx-61dcf',
    storageBucket: 'banx-61dcf.firebasestorage.app',
    androidClientId: '1076947278008-c06v4koc7beivo80ot2tt985l4f2c3l8.apps.googleusercontent.com',
    iosClientId: '1076947278008-2id28gld92uacqat1tvboj1ucschlt70.apps.googleusercontent.com',
    iosBundleId: 'com.james.dev.banx',
  );

}